#cloud-config TEMPLATE FILE IF NEEDED
package_upgrade: false
runcmd:
  # Execute update script added during image build
  - /usr/local/bin/nextcloud-update.sh
  # Execute bootstrap script added during image build
  - /usr/local/bin/nextcloud-bootstrap.sh
  