---
## The generic directory /var/containers/{{ project_id }}
## for LXD container persistent storage must be created
## Further project-specific container directories should be
## added here
## -----------------------------------------------------------

## Directories for project-specific LXD container persistent storage
## -----------------------------------------------------------------

- name: Create a directory to mount in module containers
  file:
    path: "/var/containers/{{ project_id }}"
    state: directory
    mode: '0755'


### Nextcloud directories

- name: Create a directory for nextcloud containers
  file:
    path: "/var/containers/{{ project_id }}/nextcloud"
    state: directory
    mode: '0755'


- name: Create a directory for nextcloud container config
  file:
    path: "/var/containers/{{ project_id }}/nextcloud/config"
    state: directory
    mode: '0755'


- name: Create a directory for nextcloud container data
  file:
    path: "/var/containers/{{ project_id }}/nextcloud/data"
    state: directory
    mode: '0755'


- name: Create a directory for nextcloud custom apps
  file:
    path: "/var/containers/{{ project_id }}/nextcloud/custom_apps"
    state: directory
    mode: '0755'
